/**
 * @file This file contains all the TypeScript type definitions and interfaces
 * used throughout the application. It serves as the single source of truth
 * for the game's data structures.
 */

// --- Foundational Types ---

/**
 * Represents a 2D vector or a coordinate point.
 */
export interface Vector2D {
  x: number;
  y: number;
}

/**
 * The base interface for all objects that exist within the game world.
 */
export interface GameObject {
  id: string; // Unique identifier
  position: Vector2D; // Position coordinates
  size: { width: number; height: number }; // Dimensions
}

// --- Environmental Objects ---

/**
 * A destructible obstacle in the game world.
 */
export interface Obstacle extends GameObject {
    health: number; // Current health
    maxHealth: number; // Maximum health
}

/**
 * An explosive barrel that can be detonated.
 */
export interface ExplosiveBarrel extends GameObject {
    health: number; // Usually low, explodes on any damage
    // Fix: Add maxHealth to make it structurally compatible with Obstacle for targeting systems.
    maxHealth: number;
    velocity?: Vector2D; // Velocity if thrown by a boss
}

/**
 * A visual and damaging effect created by an explosion.
 */
export interface Explosion extends GameObject {
    createdAt: number; // Timestamp of creation for animation
    duration: number; // How long the explosion lasts
    damage: number; // Damage dealt to entities within its radius
}

/**
 * An area-of-effect on the ground that can deal damage or apply status effects.
 */
export interface DamageZone extends GameObject {
  type: 'fire' | 'poison' | 'goop'; // Type of zone
  damage: number; // Damage per second (0 for goop)
  duration: number; // How long the zone lasts
  createdAt: number; // Timestamp of creation
  slow?: number; // Slow multiplier (e.g., 0.5 for 50% slow)
}

/**
 * A temporary visual effect, like an afterimage from teleporting.
 */
export interface VisualEffect {
  id: string;
  position: Vector2D;
  size: { width: number; height: number };
  createdAt: number;
  duration: number;
  type: 'teleport_afterimage' | 'focus_ring';
  color?: string; // Color of the effect
  targetId?: string; // For effects that follow an entity
}


// --- Pickups ---

/** A pickup that restores player health. */
export interface HealthPack extends GameObject {}

/** A pickup that restores player shield. */
export interface ShieldPack extends GameObject {}

/** A chest that grants a random temporary buff. */
export interface TreasureChest extends GameObject {}

/**
 * An orbital that circles the player, dealing contact damage.
 */
export interface Orbital extends GameObject {
  ownerId: string; // The ID of the entity it orbits
}

/**
 * The definition of an effect from an upgrade choice.
 */
export type UpgradeEffect =
  | { type: 'STAT_MOD'; stat: 'maxHealth' | 'speed' | 'gemMagnetRadius' | 'thornsDamage' | 'maxShield' | 'baseDamage'; op: 'add'; value: number; }
  | { type: 'STAT_MOD'; stat: 'maxHealth' | 'speed' | 'damageMultiplier' | 'fireRate' | 'bulletSpeed' | 'critChance' | 'critDamage'; op: 'multiply'; value: number; }
  | { type: 'WEAPON_MOD'; mod: 'piercing' | 'bulletCount'; value: number; }
  | { type: 'HEAL'; amount: number; } // Heals for a percentage of max HP
  | { type: 'ADD_SHIELD'; amount: number; } // Adds a flat amount of shield
  | { type: 'ORBITAL_SHIELD'; count: number; damage: number; speed: number; radius: number; };

/**
 * A temporary buff granted to the player.
 */
export interface Buff {
  id: string;
  title: { en: string; zh: string; };
  description: { en: string; zh: string; };
  duration: number; // Duration in milliseconds
  createdAt: number; // Timestamp of creation
  effects: UpgradeEffect[]; // The stat modifications applied by the buff
  color: string; // Color for the UI element
}

// --- Entities & Weapons ---

/**
 * Defines the properties of a weapon. This can be a predefined weapon
 * or one generated by the Gemini AI.
 */
export interface Weapon {
  name: { en: string; zh: string; }; // English and Chinese names
  category: 'smg' | 'rifle' | 'shotgun' | 'launcher' | 'special'; // Weapon category
  damage: number; // Base damage per projectile
  fireRate: number; // Shots per second
  bulletSpeed: number; // Speed of projectiles
  color: string; // Color of projectiles
  quality: number; // An overall score of the weapon's power
  piercing?: number; // How many enemies a bullet can pass through
  bulletCount?: number; // Number of projectiles per shot (for shotguns)
  critChance?: number; // Critical hit chance (0.0 to 1.0)
  critDamage?: number; // Critical hit damage multiplier (e.g., 1.5)
  durability?: number; // Current reserve ammo
  maxDurability?: number; // Maximum reserve ammo
  onImpact?: { // Special effect when a bullet hits or expires
    type: 'fire' | 'poison' | 'goop';
    size: { width: number; height: number };
    duration: number;
    damage: number;
  };
  clipSize?: number; // Magazine capacity
  ammoInClip?: number; // Current ammo in the magazine
  reloadTime?: number; // Time to reload in milliseconds
}

/**
 * A single choice presented to the player upon leveling up.
 */
export interface UpgradeChoice {
  id: string;
  title: { en: string; zh: string; };
  description: { en: string; zh: string; };
  effects: UpgradeEffect[];
  isCursed?: boolean; // Is this a high-risk, high-reward cursed upgrade?
  isArtifact?: boolean; // Is this a rare and powerful artifact upgrade?
}

/**
 * The player character.
 */
export interface Player extends GameObject {
  name: string;
  health: number;
  maxHealth: number;
  shield: number; // Current shield points
  maxShield: number; // Maximum shield points
  shieldAbsorption?: number; // Percentage of damage absorbed by shield (e.g., 0.75)
  weapons: Weapon[]; // All weapons the player possesses (not used in current implementation, `equippedWeapons` is used instead)
  equippedWeaponIndex: number; // Index of the currently used weapon in `equippedWeapons`
  speed: number; // Movement speed
  baseDamage: number; // Flat damage bonus added to all weapons
  damageMultiplier: number; // Multiplicative damage bonus from upgrades
  thornsDamage?: number; // Damage dealt to enemies on contact
  orbitals?: { // Properties of the player's orbitals
    count: number;
    damage: number;
    speed: number;
    radius: number;
    angle: number;
  };
  level: number;
  xp: number;
  xpToNextLevel: number;
  gemMagnetRadius: number; // Radius for attracting XP gems
  invincibleUntil?: number; // Timestamp until which the player is invincible after taking damage
  artifacts: UpgradeChoice[]; // List of powerful, unique artifacts acquired
  brokenWeaponCount: number; // Counter for a specific achievement
  visualState: 'idle' | 'running'; // For sprite animation
  shotsWithCurrentLauncher: number; // Used by AI to decide when to switch away from a launcher
  statusEffects?: { type: 'poison'; expiresAt: number; appliedAt: number; }[]; // Active status effects on the player
  lastDoTDamageTime?: number; // Timestamp of the last Damage over Time tick
  isReloading?: boolean; // Is the player currently reloading?
  reloadUntil?: number; // Timestamp when reloading finishes
  buffs: Buff[]; // List of active temporary buffs
  lastPosition?: Vector2D; // Position in the previous frame for stuck detection
  timeAtLastPosition?: number; // Timestamp for stuck detection
  teleportedByBossAt?: number; // Timestamp when a boss teleported the player, for stuck detection
}

/** AI behavior profile for friendly allies. */
export type AIBehavior = 'resolute_recruit' | 'evasion_first' | 'daring_breakout';

/**
 * State for the AI-controlled auto-walk feature.
 */
export interface AutoWalkState {
    target: Vector2D | null;
    lastDirectionChange: number;
    randomDirection: Vector2D;
    isUnstucking?: boolean;
    unstuckUntil?: number;
    unstuckDirection?: Vector2D;
    isBreakingOut?: boolean; // For forcefully moving away from a close enemy
    breakoutUntil?: number;
    breakoutDirection?: Vector2D;
    lastPosition?: Vector2D;
    stuckTime?: number;
    weaponSwitchCooldown?: number; // Cooldown for AI weapon switching
}

/**
 * A friendly NPC ally that assists the player.
 */
export interface Ally extends GameObject {
  name: string;
  health: number;
  maxHealth: number;
  weapon: Weapon; // Ally's weapon
  speed: number;
  aiBehavior: AIBehavior;
  autoWalkState: AutoWalkState;
  lastShotTime: number;
  level: number;
  disappearsAt: number; // Timestamp when the ally despawns
  dialogue?: { text: string; displayUntil: number; }; // Dialogue bubble content and display time
  lastDialogueTime?: number;
  spawnTime: number; // Timestamp of creation, used for unstuck checks
  isSpawnPositionChecked?: boolean; // Flag to check if the initial spawn position was valid
  visualState: 'idle' | 'running'; // For sprite animation
  lastPosition?: Vector2D; // Position in the previous frame, for stuck detection
  timeAtLastPosition?: number; // Timestamp for stuck detection
  invincibleUntil?: number; // Timestamp until which the ally is invincible after taking damage
}

/**
 * An enemy monster.
 */
export interface Monster extends GameObject {
  name?: { en: string; zh: string; }; // Custom name for Bosses or Thematic monsters
  health: number;
  maxHealth: number;
  speed: number;
  xpValue: number; // XP granted on defeat
  level?: number; // Monster's level, usually the wave it spawned on
  type: 'normal' | 'elite' | 'shooter' | 'shotgun_shooter' | 'healer' | 'summoner' | 'minion' | 'boss' | 'wisp' | 'bloater' | 'lich_guard';
  weapon?: Weapon; // A weapon the monster may have picked up
  empoweredLevel?: number; // How many XP gems this monster has absorbed
  isHidden?: boolean; // Is the monster hidden (e.g., during a wisp teleport)
  visualState?: 'idle' | 'running'; // For sprite animation
  dialogue?: { text: string; displayUntil: number; }; // For boss taunts
  diesAt?: number; // Timestamp when death animation starts
  deathEffect?: 'explode' | 'run_wild' | 'spin_fade' | 'run_and_explode'; // The type of death animation
  deathAnimationData?: { // Data for the specific animation
    runDirection?: Vector2D;
    lastRunDirectionChange?: number;
    spinAngle?: number;
  };
  phase?: number; // Current phase of a boss fight
  healthThresholds?: number[]; // Health percentages that trigger boss phase changes
  aiState?: { // State machine for complex AI behaviors
    type: 'strafe' | 'hesitate' | 'avoiding' | 'teleporting' | 'throwing' | 'charging' | 'dashing' | 'unstucking' | 'barrage';
    lastActionTime: number;
    strafeDirection?: number;
    isMoving?: boolean;
    lastAttackTime?: number;
    isChargingAttack?: boolean;
    chargeStartTime?: number;
    dashTarget?: Vector2D; // (Boss) Target position for a dash
    dashEndTime?: number; // (Boss) Timestamp when the dash ends
    lastMinionSpawnTime?: number; // (Boss) Timestamp of last minion spawn
    unstuckUntil?: number;
    teleportData?: { from: Vector2D; to: Vector2D; startTime: number; }; // (Wisp) Teleportation data
    lastDialogueTime?: number; // Cooldown for boss taunts
    lastSpecialAttackTime?: number;
    barrageAngle?: number; // For Gatling Eye boss
    isExhaustedUntil?: number; // Cooldown after a special attack
    lichGuardId?: string; // For Arch-Summoner boss
  };
  lastSpawnTime?: number; // (Summoner) Timestamp of last spawn
  lastHealTime?: number; // (Healer) Timestamp of last heal
  orbitalHitCooldownUntil?: number; // Cooldown after being hit by an orbital
  timeAtLastPosition?: number; // Timestamp for stuck detection
  lastPosition?: Vector2D; // Position in the previous frame for stuck detection
  facingAngle?: number; // Angle in radians the monster is facing (for aiming)
  invincibleUntil?: number; // (Boss) Timestamp for invincibility during phase changes
  lastDoTDamageTime?: number; // Timestamp of the last Damage over Time tick
  spawnTime?: number; // Timestamp of monster creation
}

// --- Projectiles ---

/**
 * A projectile fired by the player or an ally.
 */
export interface Bullet extends GameObject {
  ownerId: string;
  velocity: Vector2D;
  damage: number;
  color: string;
  piercingLeft: number; // How many more enemies it can pierce
  createdAt: number;
  onImpact?: Weapon['onImpact']; // Carries the onImpact effect from the weapon
}

/**
 * A standard projectile fired by an enemy.
 */
export interface EnemyBullet extends GameObject {
  velocity: Vector2D;
  damage: number;
  color: string;
  sourceType: Monster['type'] | 'event';
  sourceId: string;
  bounced?: boolean;
  createdAt: number;
  lifespan?: number; // How long the bullet exists in milliseconds
  onImpact?: Weapon['onImpact']; // Boss bullets can have special effects
}

/**
 * A homing projectile fired by an enemy.
 */
export interface HomingEnemyBullet extends EnemyBullet {
  targetId: string; // The ID of the entity it's tracking
  turnSpeed: number; // How quickly it can change direction
}

// --- Drops ---

/** A weapon dropped on the ground. */
export interface WeaponDrop extends GameObject {
  weapon: Weapon;
}

/** An experience gem dropped by a monster. */
export interface ExperienceGem extends GameObject {
  xpValue: number;
  targetMonsterId?: string; // ID of a monster that is absorbing this gem
}

// --- UI & Game State ---

/**
 * A floating damage number that appears when an entity takes damage.
 */
export interface DamageNumber {
    id: string;
    position: Vector2D;
    amount: number;
    createdAt: number;
    isCrit: boolean; // Was this a critical hit?
    isDoT?: boolean; // Was this from a Damage over Time effect?
    isWallDamage?: boolean; // Was this damage to an obstacle?
}

/**
 * An entry on the local leaderboard.
 */
export interface LeaderboardEntry {
    name: string;
    score: number;
    wave: number;
}

/**
 * An achievement or announcement popup message.
 */
export interface Achievement {
  id: string;
  title?: string;
  message: string;
  createdAt: number;
  isExiting?: boolean; // For fade-out animation
  category?: 'achievement' | 'announcement' | 'special' | 'praise' | 'game_remark'; // UI category
}

/**
 * A single entry in the dialogue history log.
 */
export interface DialogueEntry {
  id: string;
  text: string;
  speaker: string;
  createdAt: number;
  isExiting?: boolean; // For fade-out animation
  speakerType?: 'ally' | 'boss' | 'thematic' | 'game'; // For color-coding
}

/** Game difficulty level. */
export type Difficulty = 'easy' | 'normal' | 'hard' | 'hell';

/**
 * Modifiers applied to game values based on the selected difficulty.
 */
export interface DifficultyModifiers {
  playerDamageTaken: number;
  monsterHealth: number;
  monsterSpeed: number;
  xpGain: number;
  monsterDamage: number;
}

/**
 * Defines a theme for a wave of monsters, including a boss and modifiers.
 */
export interface WaveTheme {
    title: { en: string, zh: string };
    description: { en: string, zh: string };
    bossName: { en: string, zh: string };
    flavorText?: { en: string, zh: string }; // Optional flavor text for the wave
    monsterNames?: Partial<Record<Monster['type'], { en: string, zh: string }>>; // Thematic names for standard monsters
    modifiers: {
        health?: number;
        speed?: number;
        count?: number;
    };
}

/**
 * A random, temporary event that affects gameplay for a short duration.
 */
export interface GameEvent {
  type: 'meteor_shower' | 'treasure_trove';
  title: { en: string; zh: string };
  expiresAt: number;
  lastTick?: number; // for timed effects like meteor shower
}

/**
 * The definition of an effect provided by a collectible card.
 */
export type CardEffect = { type: 'STAT_MOD', stat: keyof Player, op: 'add' | 'multiply', value: number };

/**
 * The definition of a collectible card that provides permanent bonuses.
 */
export interface Card {
  id: string;
  name: { en: string, zh: string };
  description: { en: string, zh: string };
  rarity: 'common' | 'rare' | 'epic';
  effects: CardEffect[];
}

/**
 * The player's persistent profile, saved in localStorage.
 */
export interface PlayerProfile {
  cardPacks: number; // Number of unopened card packs
  cardInventory: { cardId: string; count: number }[]; // All collected cards and their counts
  equippedCardIds: string[]; // IDs of the cards currently equipped for the next run
}

// Fix: Add a unified AIResult interface for all monster AI handlers.
/**
 * The result structure for a monster's AI tick.
 */
export interface AIResult {
    updatedMonster: Monster;
    newEnemyBullets?: EnemyBullet[];
    newHomingBullets?: HomingEnemyBullet[];
    newMonsters?: Monster[];
    newExplosiveBarrels?: ExplosiveBarrel[];
    newVisualEffects?: VisualEffect[];
    newDialogueHistory?: DialogueEntry[];
    updatedOtherMonsters?: Monster[];
}

/**
 * The main game state tree. This object contains all the data
 * needed to represent the current state of the game world.
 */
export interface GameState {
  player: Player;
  equippedWeapons: (Weapon | null)[]; // Player's equipped weapons (max 3)
  allies: Ally[];
  monsters: Monster[];
  bullets: Bullet[];
  enemyBullets: EnemyBullet[];
  homingEnemyBullets: HomingEnemyBullet[];
  weaponDrops: WeaponDrop[];
  experienceGems: ExperienceGem[];
  damageNumbers: DamageNumber[];
  obstacles: Obstacle[];
  explosiveBarrels: ExplosiveBarrel[];
  explosions: Explosion[];
  damageZones: DamageZone[];
  visualEffects: VisualEffect[];
  healthPacks: HealthPack[];
  shieldPacks: ShieldPack[];
  treasureChests: TreasureChest[];
  orbitals: Orbital[];
  camera: Vector2D; // Camera position (top-left corner)
  keys: Record<string, boolean>; // State of keyboard keys
  score: number;
  wave: number;
  monstersToKillForNextWave: number;
  monstersKilledThisWave: number;
  isWaitingForBossClear: boolean; // Is the game waiting for the field to clear before spawning a boss?
  isBossWave: boolean; // Is it currently a boss wave?
  isGameOver: boolean;
  isLevelingUp: boolean; // Is the level-up screen active?
  isPaused: boolean;
  currentWaveTheme: WaveTheme | null;
  waveThemeDisplayUntil: number; // Timestamp for wave announcement UI
  levelUpChoices: UpgradeChoice[];
  lastShotTime: number;
  lastMonsterSpawnTime: number;
  lastTreasureChestSpawnTime: number;
  screenShake: number; // Magnitude of the screen shake effect
  settings: {
    autoFire: boolean;
    autoWalk: boolean;
    autoSwitchWeapon: boolean; // AI automatically switches to the best weapon
    screenShakeEnabled: boolean;
    language: 'zh' | 'en';
    showOnScreenControls: boolean;
    aiBehavior: AIBehavior;
  };
  autoWalkState: AutoWalkState;
  leaderboard: LeaderboardEntry[];
  achievements: Achievement[];
  dialogueHistory: DialogueEntry[];
  difficulty: Difficulty;
  difficultyModifiers: DifficultyModifiers;
  encounteredMonsters: Set<Monster['type']>; // Tracks which monster types have been seen for intro popups
  encounteredThematicMonsters: Set<string>; // Tracks thematic monsters for dialogue variety
  monsterIntro: { type: Monster['type']; displayUntil: number; } | null; // Data for the new monster intro popup
  targetedMonsters: ((Monster & { lastHitTime: number; lockedUntil?: number; }) | null)[]; // The monsters whose info is shown in the HUD (fixed to 3 slots)
  targetedObstacle: (Obstacle & { lastHitTime: number; lockedUntil?: number; }) | null; // The obstacle whose info is shown in the HUD
  nextAllySpawnTime: number;
  isInitialAllySpawned: boolean;
  unlockedAchievements: Set<string>; // Set of achievement IDs unlocked in the current run
  killCounts: Record<Monster['type'], number>; // Tracks kills for each monster type for achievements
  lastObstacleRefreshWave: number; // Last wave where obstacles were refreshed
  activeEvent: GameEvent | null;
}